[project]
name = "Restaurant"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "PavelCode5426", email = "perezpavel5426@gmial.com" }
]
dependencies = [
    "flet-embed",
    "flet_route",
    "tortoise",
    "tortoise-orm",
]


#[tool.poetry.dependencies]
#tortoise-orm = "0.21.3"
#flet_route = "0.3.3"
#flet = "0.27.6"

[tool.flet]
org = "com.pavelcode5426" # --org
product = "Restaurant App" # --product
company = "PavelCode5426" # --company
copyright = "Copyright (C) 2024 by MyCompany" # --copyright
build_number = 4 # --build-number

[tool.flet.app]
exclude = ["assets"]

[tool.flet.compile]
app = true
packages = true
cleanup = true